### PR TITLE
Feature/footer

### PR DESCRIPTION
**Pull request by lokiiarora**

### CODE REVIEW

**Comment by varora1406** [comment]
Please make following changes - 
* Add redirection to 'addResources' page on click of 'Having a lead'
* And on click of rest two buttons (Volunteer and data partner one), can you redirect it to https://twitter.com/COVResourcesIn ?

**Comment by lokiiarora** [comment]
Ack !
Adding it in.

**Comment by lokiiarora** [comment]
@varora1406 added it in !
Do check !

**Comment by varora1406** [comment]
works 👍

**Review by varora1406 — APPROVED** [review]

**Pull request merged**
